# create array

In [69]:
import numpy as np

my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)

#Print out array
my_array1

array([1, 2, 3, 4])

# Make multi-dimensional array

In [70]:
# Make another list
my_list2 = [11,22,33,44]

#Make a list of lists
my_lists = [my_list1,my_list2]

#Make multi-dimensional array
my_array2 = np.array(my_lists)

#Show array
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

#  get the size of the array

In [71]:
my_array2.shape

(2, 4)

# number of rows

In [72]:
my_array2.shape[0]

2

# number of coulmns

In [73]:
my_array2.shape[1]

4

# Find out the data type of the array

In [74]:
my_array2.dtype

dtype('int32')

# An empty array

In [75]:
np.empty(5)


array([ 1.,  1.,  1.,  1.,  1.])

In [76]:
np.empty((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

# Zeros

In [77]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

# ones

In [78]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

# Identity array

In [79]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

# Using a range

In [80]:
np.arange(5)

array([0, 1, 2, 3, 4])